# Generated by Django 3.0 on 2020-03-23 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ano',
            options={'verbose_name': 'Año', 'verbose_name_plural': 'Años'},
        ),
    ]
